### ISSUE TITLE
Activate Visual Studio Code preview tooltip for bmak property

### ISSUE THREAD

**Issue by azerpas** [char/bpre#10]
That would help a lot for debugging.

The ternary operator in this line https://github.com/char/bpre/blob/ff4f024cd2808b0e35afcdf9793ba56abe85260f/akamai/1.7.js#L5 is preventing the activation of VS Code preview function.     

### With the ternary operator
<img width="385" alt="with" src="https://user-images.githubusercontent.com/19282069/132641020-e0c07084-f502-4cd3-98ee-694e8f60b1bf.png">

### Without it
<img width="737" alt="without" src="https://user-images.githubusercontent.com/19282069/132641188-5a620158-97f3-4f90-959a-616f666a06a3.png">

By removing the *if then* and just keeping the *else*, we could access the preview functionnality in the whole file.       
@char what do you think? I could add a comment like you did here: https://github.com/char/bpre/blob/ff4f024cd2808b0e35afcdf9793ba56abe85260f/akamai/1.7.js#L247-L252

**Comment by voidstar0** [comment]
Noticed this as well. Pushing a fix to [akamai-deobfuscator](https://github.com/char/akamai-deobfuscator) to handle this.
