### ISSUE TITLE
Migrate to TypeScript

### ISSUE THREAD

**Issue by azerpas** [char/bpre#9]
By migrating each minified JS file to TypeScript, we might benefit from the type system.

**Comment by sleeyax** [comment]
This is one of the very few projects where it doesn't make sense to use typescript imo. The project purpose is to document original, deobfuscated source code so a type system would only get in the way and could stray away too far from the original source. It would make sense to use typescript if you're writing a sensor data generator for example though.

**Comment by azerpas** [comment]
@sleeyax fair, closing 🙂
